// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDCTswSDfpdkfdh4jCZdyZIHSPfIwf_Y',
    appId: '1:607423363774:web:99640eaf5ed9d0e857bcef',
    messagingSenderId: '607423363774',
    projectId: 'stumble-175cb',
    authDomain: 'stumble-175cb.firebaseapp.com',
    storageBucket: 'stumble-175cb.appspot.com',
    measurementId: 'G-QT2Y6HMW0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPctRQlnbFKXNflUCWxZBV07DKZxChemI',
    appId: '1:607423363774:android:1ec7e2238ab0792057bcef',
    messagingSenderId: '607423363774',
    projectId: 'stumble-175cb',
    storageBucket: 'stumble-175cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ek460Q28UDUTjlq3VrglvRzZ5MOamOA',
    appId: '1:607423363774:ios:a2c95b21c8667eb557bcef',
    messagingSenderId: '607423363774',
    projectId: 'stumble-175cb',
    storageBucket: 'stumble-175cb.appspot.com',
    iosBundleId: 'com.getstumbleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ek460Q28UDUTjlq3VrglvRzZ5MOamOA',
    appId: '1:607423363774:ios:c6a110275738c3b757bcef',
    messagingSenderId: '607423363774',
    projectId: 'stumble-175cb',
    storageBucket: 'stumble-175cb.appspot.com',
    iosBundleId: 'com.getstumbleapp',
  );
}
